### PR TITLE
fix license headers

### PR DESCRIPTION
**Pull request by agaida**

### CODE REVIEW

**Comment by palinek** [comment]
merged in @f3cb5bfe96c5b0a5b53f5ed46e40504456647fad, @2dbdb36408c5ce1b13456c48186193ff6b8de5fe

**Comment by palinek** [comment]
oh boy... I've just noticed the new license discussion/proposal

@jleclanche @agaida should we revert this or we will just replace it in the following commit(s) by new license header

**Comment by jleclanche** [comment]
@palinek I have hard-reverted.

**Comment by agaida** [comment]
@jleclanche thanks

**Pull request closed without merging**
