### PR TITLE
Remove the provider for power actions

### PR DESCRIPTION
**Pull request by paulolieuthier**
lxqt-session's lxqt-leave provides them as well.

Fixes lxde/lxqt#476.

### CODE REVIEW

**Comment by paulolieuthier** [comment]
@pmattern continue the discussion on irc: runner's menu will continue to work from liblxqt.

**Comment by pmattern** [comment]
Well, as I understood it replacing menu entries derived from liblxqt by using desktop entry files as provided by lxqt-session *by default* was exactly the point of #476, see https://github.com/lxde/lxqt/issues/476#issuecomment-77061340.

**Comment by paulolieuthier** [comment]
@pmattern that's the conclusion for runner's suggestions, not for the configuration menu.

**Comment by pmattern** [comment]
Err, I didn't understand it that way and I don't think it makes sense either. The main idea was to get rid of duplicate maintenance effort. And this affects configuration menu even more than text box.

Btw. upon reading your last post I tested text box again - dupes herein are indeed gone now.

**Comment by paulolieuthier** [comment]
@pmattern lxqt-leave gets the power actions from liblxqt as well, so the maintenance effort will remain. It's much easier this way.

**Pull request merged**
