### PR TITLE
Sets the command list to use alternating row colors

### PR DESCRIPTION
**Pull request by luis-pereira**
Enhances the readability.

### CODE REVIEW

**Comment by luis-pereira** [comment]
@PCMan @jleclanche @paulolieuthier your two cents

**Comment by paulolieuthier** [comment]
Looks a little bit weird if using a theme that uses transparency (Dark, for example). Maybe the themes can be enhanced to fix that.

**Comment by jleclanche** [comment]
probably @intialonso a better ping than me here. I'm cool with the idea, just need to see how it looks.

**Comment by luis-pereira** [comment]
Shots with Breeze and Fusion
lxqt-runner-alternating-row-colors-breeze
lxqt-runner-alternating-row-colors-fusion

**Comment by paulolieuthier** [comment]
@luis-pereira I mean, lxqt's themes, not qt widget styles.

**Comment by paulolieuthier** [comment]
But for me, it's gtm anyway.

**Comment by intialonso** [comment]
I understand that the list is a HtmlDelegate, and cant be themed from QSS. We had a discussion about this sometime ago in #347

**Comment by luis-pereira** [comment]
@paulolieuthier the lxqt-runner.qss doesn't style the command list.
Example: https://github.com/lxde/lxqt-common/blob/master/themes/Frost/lxqt-runner.qss#L62

**Comment by paulolieuthier** [comment]
@luis-pereira yes, you're right. But that's how it looks here:

screen

**Comment by luis-pereira** [comment]
@paulolieuthier Not sure I understood you. Everything is as usual with the exception of the alternating colors that don't depend on LXQt theme.

**Comment by paulolieuthier** [comment]
@luis-pereira what I meant was to show you the transparency. But that's not necessarily a problem, go ahead and merge it, it's better this way.

**Comment by luis-pereira** [comment]
@paulolieuthier Now I understand. Well, transparency is set by the LXQt theme. 
screen-2015-01-29-11-18-14

@intialonso The alternate background color can be themed with qss
```
#commandList {
    alternate-background-color: yellow;
} 
```
And we got this eye blinding screenshot:
screen-2015-01-29-11-53-22

**Comment by intialonso** [comment]
Great, I will take a look into  the color schemes to see how this could work with each theme.

**Comment by luis-pereira** [comment]
@intialonso Great :smile:

**Comment by intialonso** [comment]
Well for now we will have to leave this without themes customization. At least untill we can style the foreground colors, hover and selected states, etc.

**Pull request merged**
