### PR TITLE
Replace deprecated QtScript with QJSEngine.

### PR DESCRIPTION
**Pull request by goetzc**
This is for lxde/lxqt#1080.

### CODE REVIEW

**Comment by paulolieuthier** [comment]
I'm not sure how bad is pulling the whole Qml just for this, but we're pulling QtScript anyway...

**Comment by paulolieuthier** [comment]
This must enter in the changelog.

**Comment by palinek** [comment]
I'm also for finding some "lighter solution"...

**Comment by goetzc** [comment]
Do you thing that it is to much overhead? Maybe this library is lighter, [muparser](http://muparser.beltoforion.de/), which is a math parser.

According to KDE's systemmonitor, in my setup: 
libQt5Qml.so.5.7.0 adds 92 KB.
libQt5Script.so.5.7.0 adds 212 KB.
to the lxqt-runner process

**Comment by paulolieuthier** [comment]
Good to know its memory footprint is that low. What is the size of Qt5Declarative, installed?

**Comment by goetzc** [comment]
In Arch Linux i686 it is 17 MB. The good news is that it is also a dependency of sddm, solid (dependency of lxqt-panel and lxqt-powermanagment, qt5-webchannel, and more, so it should already be installed.

**Comment by paulolieuthier** [comment]
@palinek what do you think about it now?

**Comment by palinek** [comment]
> In Arch Linux i686 it is 17 MB. The good news is that it is also a dependency of sddm, solid (dependency of lxqt-panel and lxqt-powermanagment), qt5-webchannel, and more, so it should already be installed.

libkf5solid doesn't depend on libqt5qml on debian. So just the sddm, which one don't need to use.

The muparser seems to be a good choice... and it is even [packaged in debian stable](https://packages.debian.org/search?keywords=libmuparser&searchon=names&suite=stable&section=all) (and if it's there, it should be everywhere else :smile:)

**Comment by palinek** [comment]
@paulolieuthier, @goetzc please, have a look on the #45 (the implementation wit libmuparser)

**Comment by paulolieuthier** [comment]
Yes, being on Debian stable, muparser should be ubiquitous. And it's much more lightweight, and probably faster (not that the difference is noticeable, but still).

**Comment by PCMan** [comment]
@palinek @paulolieuthier 
Please also review my simple PR on the same issue, which IMHO is a better approach.
https://github.com/lxde/lxqt-runner/pull/46
Thank you.

**Comment by palinek** [comment]
closing in flavour of #45 or #46...

**Pull request closed without merging**
