### PR TITLE
AppLinkItem: Make genericName searchable

### PR DESCRIPTION
**Pull request by palinek**
needs lxde/menu-cache#15

fixes lxde/lxqt#1278

### CODE REVIEW

**Comment by agaida** [comment]
so in other words - we should not merge this change until the changed menu cache (>=1.1.0) is available in distributions. Until this happends i would like to call this PR strictly blocked.

**Comment by palinek** [comment]
> we should not merge this change until the changed menu cache (>=1.1.0) is available in distributions.

Right, amended the commit to require libmenu-cache 1.1.0

**Comment by agaida** [comment]
menu-cache 1.1.0 has be releases and should be available in all major distributions - so we can merge that now. @palinek, what do you think?

**Comment by palinek** [comment]
> menu-cache 1.1.0 has be releases and should be available in all major distributions - so we can merge that now. @palinek, what do you think?

If so... feel free to push the button

**Pull request merged**
