### PR TITLE
Math: Use libmuparser for math evaluation

### PR DESCRIPTION
**Pull request by palinek**
ref  lxde/lxqt#1080

### CODE REVIEW

**Comment by paulolieuthier** [comment]
Are you able to capture exceptions? All lxqt components are by default compiled with `-fno-exceptions` and catching them should not be possible.

**Comment by PCMan** [comment]
IMHO, it's much simpler to just call an external calculator such as "bc" to get the result on demand.
The command is only invoked when the math calculation is actually required and no library or any scripting language engine need to be imported. This is how UNIX should work.

**Comment by PCMan** [comment]
Please also review my PR using bc as a very simple alternative.
https://github.com/lxde/lxqt-runner/pull/46

**Comment by palinek** [comment]
> Are you able to capture exceptions? All LXQt components are by default compiled with -fno-exceptions and catching them should not be possible AFAICT.

Of course I'm catching the exceptions...see the changes in CMakeLists...

**Comment by palinek** [comment]
> Are you able to capture exceptions? All LXQt components are by default compiled with -fno-exceptions and catching them should not be possible AFAICT.

Of course I'm catching the exceptions...see the changes in CMakeLists...

**Comment by palinek** [comment]
> Are you able to capture exceptions? All LXQt components are by default compiled with -fno-exceptions and catching them should not be possible AFAICT.

Of course I'm catching the exceptions...see the changes in CMakeLists...

**Comment by palinek** [comment]
> Are you able to capture exceptions? All LXQt components are by default compiled with -fno-exceptions and catching them should not be possible AFAICT.

Of course I'm catching the exceptions...see the changes in CMakeLists...

**Comment by palinek** [comment]
> Are you able to capture exceptions? All LXQt components are by default compiled with -fno-exceptions and catching them should not be possible AFAICT.

Of course I'm catching the exceptions...see the changes in CMakeLists...

**Comment by palinek** [comment]
> Are you able to capture exceptions? All LXQt components are by default compiled with -fno-exceptions and catching them should not be possible AFAICT.

Of course I'm catching the exceptions...see the changes in CMakeLists...

**Comment by palinek** [comment]
> IMHO, it's much simpler to just call an external calculator such as "bc" to get the result on demand.
The command is only invoked when the math calculation is actually required

I don't agree with spawning external process here. Especialy with the "equal sign on beginning" enhancement. I didn't measure it but I'm sure the performance with tiny library is reasonably better than spawning the external process.

**Comment by PCMan** [comment]
@palinek In theory, forking a new process is slower than just calling a function. That's true.
In reality, it does not matter for such a simple case. It is not performance critical at all.
The benefit of an external process is obvious. If you don't use it, don't pay for it.
Users who never need this feature does not even need to install bc.
It's a standard UNIX tool with POSIX standard syntax so there won't be compatibility problems.
Nobody will do very complicated calculations in lxqt-runner I guess. The feature is only useful when you need a quick answer for simple calculations. Libmuparser is a great library, but it seems to be overkill in this case. Implementing a powerful calculator app with it, on the other hand, should be a great addon to LXQt, I think.

**Comment by PCMan** [comment]
Let me show you some numbers:
> time for (( i=0; $i < 1000; i=$i+1 )); do echo 1*2+3 | bc > /dev/null; done
real	0m0.688s
user	0m0.070s
sys	0m0.140s
Tested on Linux desktop with Intel core i7.
With the cache I added, there is only one invocation of "bc" for each different calculation.
So the performance problem, obviously, is never an issue here.

**Comment by PCMan** [comment]
Yet another reason why I favor the old UNIX tool.
https://qa.debian.org/popcon.php?package=bc
See the popularity contest of Debian packages.
About 1/3 of the debian users are constantly using this tool. (For muparser, it's 0.05%)
That means, "bc" is not a new dependency for those users since it's already part of the system.

**Comment by PCMan** [comment]
Anyway, muparser is a good solution as well. At least it's much better than including a full blown scripting engine for such a simple feature.

**Comment by goetzc** [comment]
I will share here my findings with the current code.

* QJSEngine is similar to the deprecated QtScript in functionality, memory usage is very similar ~200 kB.
* muparser has virtually the same memory usage as those two Qt options. Additionally it also displays the result for the power `^` operator, in the form `a^b` where `a` and `b` are decimals. It also computes some trigonometric functions, `sin()`, `cos()`, `tan()`, and other functions like  `log2()`, `sum()`, `avg()`, [and more](http://beltoforion.de/article.php?a=muparser&hl=en&p=features&s=idDef2#idDef2). It works when the `=` sign is at the beginning or at the end of the expression.
* bc, no shared memory usage as it calls an external process. No trigonometric functions, or of any kind. The `^` operator works for decimals in the base like, a.b^c, but not for a^c.d when the exponent is a decimal number.

**Comment by paulolieuthier** [comment]
IMO, muparser it is.

**Comment by PCMan** [comment]
@goetzc Actually, bc has trigonometric functions. Instead of sin() and cos() and log(), it uses s() and c(), and l(). Anyway, it's just a simple alternative.
If other developers all support muparser, I'm ok with that, too.
@palinek However, please include my patch for the "cache" part. Because of the design of Qt data models, the compare() method is called repeatedly and the same calculation is done for several times, which is unnecessary. Caching the most recent result, as I did in my PR, can fix this.
Please include that even if you're going to use muparser or whatever solutions.

**Comment by palinek** [comment]
> However, please include my patch for the "cache" part. Because of the design of Qt data models, the compare() method is called repeatedly and the same calculation is done for several times, which is unnecessary. Caching the most recent result, as I did in my PR, can fix this.

I will... as soon as the decision, which alternative to use, is made.

Are we going to use the libmuparser or the bc?

**Comment by goetzc** [comment]
> Actually, bc has trigonometric functions. Instead of sin() and cos() and log(), it uses s() and c(), and l(). Anyway, it's just a simple alternative.

I didn't knew these names, they are very counterintuitive :/ IMO.

**Comment by paulolieuthier** [comment]
@luis-pereira, what's your opinion?

**Comment by luis-pereira** [comment]
I'm tending to @PCMan proposal. libmuparser is also a good solution. And it's already implemented.

**Comment by palinek** [comment]
>
- QJSEngine is similar to the deprecated QtScript in functionality, memory usage is very similar ~200 kB.
- muparser has virtually the same memory usage as those two Qt options.

@goetzc How did you get those memory footprints? I'm seeing this on my system:
```
$ ls -hl /usr/lib/x86_64-linux-gnu/libQt5Script.so.5.6.1 /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5.6.1 /usr/lib/x86_64-linux-gnu/libmuparser.so.2.2.3
-rw-r--r-- 1 root root 341K 2015-08-23 17:57 /usr/lib/x86_64-linux-gnu/libmuparser.so.2.2.3
-rw-r--r-- 1 root root 4.0M 2016-06-16 18:50 /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5.6.1
-rw-r--r-- 1 root root 2.4M 2016-06-13 19:43 /usr/lib/x86_64-linux-gnu/libQt5Script.so.5.6.1
`

**Comment by goetzc** [comment]
> How did you get those memory footprints? I'm seeing this on my system

Oh, I thought I mentioned it. Those values are system memory, not disk space. Those came from KDE's systemmonitor "Detailed Memory Information".

**Comment by palinek** [comment]
> Oh, I thought I mentioned it. Those values are system memory, not disk space. Those came from KDE's systemmonitor "Detailed Memory Information".

I'm not a guru for memory usage etc. I'm just curious how "small" library can have the same memory footprint as those "big" libraries.This is what I see:
- current `master` branch
```
$ pmap "$(pgrep -f lxqt-runner)" | egrep Qt5Script
00007f98596b2000   2368K r-x-- libQt5Script.so.5.6.1
00007f9859902000      4K ----- libQt5Script.so.5.6.1
00007f9859903000     72K r---- libQt5Script.so.5.6.1
00007f9859915000      4K rw--- libQt5Script.so.5.6.1
```
- `math_muparser` branch
```
$ pmap "$(pgrep -f lxqt-runner)" | egrep mupar
00007fedfb25c000    336K r-x-- libmuparser.so.2.2.3
00007fedfb2b0000   2044K ----- libmuparser.so.2.2.3
00007fedfb4af000      4K r---- libmuparser.so.2.2.3
00007fedfb4b0000      4K rw--- libmuparser.so.2.2.3
```

Note: I found following about the 2MB blocks: http://stackoverflow.com/questions/9297334/why-do-i-see-big-differences-in-memory-usage-with-pmap-for-the-same-process-on-3

**Comment by luis-pereira** [comment]
> Instead of sin() and cos() and log(), it uses s() and c(), and l()
That's what invalidate bc IMO.
"Voting" for this.

**Comment by PCMan** [comment]
@palinek Looks like most developers are in favor of this one? :-)
I'm OK with this one, too. Just don't forget to cache the calculation result.
Because of the design of Qt model/view, the same calculation will be done repeatedly when the info of an item is required. This is a waste.

**Comment by selairi** [comment]
Some years ago I was working in a project and I had to use bc in some
calculations.
This is an example of bc session. Maybe it could help to choose the best
option:

$ bc -l
bc 1.06.95
Copyright 1991-1994, 1997, 1998, 2000, 2004, 2006 Free Software Foundation,
Inc.
This is free software with ABSOLUTELY NO WARRANTY.
For details type `warranty'.
# Redefine some common functions:
define sin(x) {return s(x);}
define cos(x) {return c(x);}
define tan(x) {return s(x)/c(x);}
define atan(x) {return a(x);}
# Examples:
sin(2)
.90929742682568169539
tan(1)
1.5574077246549022305
# atan(1)*4 = Pi
atan(1)*4
3.14159265358979323844
# 120 numbers of Pi
scale = 120
atan(1)*4
3.141592653589793238462643383279502884197169399375105820974944592307\
816406286208998628034825342117067982148086513282306644
# 300 numbers of Pi
scale = 300
atan(1)*4
3.141592653589793238462643383279502884197169399375105820974944592307\
81640628620899862803482534211706798214808651328230664709384460955058\
22317253594081284811174502841027019385211055596446229489549303819644\
28810975665933446128475648233786783165271201909145648566923460348610\
454326648213393607260249141272
# Binary pi
scale = 10
obase = 2
atan(1)*4
11.0010010000111111011010101000011011
# Hexadecimal pi
obase = 16
atan(1)*4
3.243F6A86D
# Javascript like syntax
define f(x) {return sin(x)/x;}
obase = 10
for(n=1;n<10;n++) {
f(x/n)
}
.8414709848
.9588510772
.9815840901
.9896158368
.9933466535
.9953767959
.9966021082
.9973978664
.9979436556
# Integrate function f(x) = sin(x)/x using Simpson rule
define simpson(a,b,n) {
auto h,sum_even,sum_odd;
h=(b-a)/(2*n);
sum_even=0;
sum_odd=0;
for (i=1;i<=n;i++) sum_odd=sum_odd+f(a+(2*i-1)*h);
for(i=1;i<n;i++) sum_even=sum_even+f(a+2*i*h);
return ((f(a)+f(b)+4*sum_odd+2*sum_even)*h/3);
}
simpson(1,2,100)
.6593299063


2016-08-05 21:26 GMT+02:00 Luís Pereira <notifications@github.com>:

**Comment by palinek** [comment]
...added the caching mechanism.

Now thinking of the runner's memory footprint.... is it worth implementing `OurMuParser` as a Qt plugin (which will internaly use the libmuparser) and lazily load it only when the first 'calculation' is needed?

**Comment by paulolieuthier** [comment]
GTM.

**Comment by palinek** [comment]
How about the plugin?

**Comment by paulolieuthier** [comment]
I'd do it if one day we need more features like that (that need libraries). For now this is enough.

**Pull request merged**
