### PR TITLE
Updated german translation, made common for all regions.

### PR DESCRIPTION
**Pull request by ThomasVie**

### CODE REVIEW

**Comment by pmattern** [comment]
Translation itself seems fine to me.
Maybe replace "Runner Dialog" in string "Show/hide..." from context Dialog with "Runner-Dialog" to be consistent with "Runner Settings" from ConfigureDialog? Couldn't even figure out where the former is meant to appear in the first place, though. The latter applies to "Mathematics", too...

What this translation mainly made me stumble upon is that "Appearance" in ConfigureDialog is actually nonsense. This has just nothing to do with "Appearance" as used in lxqt-config-appearance, rather both settings are actually composing the positioning.
But probably something that should be handled separately from this PR. What do you think?

**Comment by ThomasVie** [comment]
Yes, the space should be replaced by a hyphen.
What do you think about translating "Runner" itself, could be "Anwendungsstarter"?

**Comment by pmattern** [comment]
> What do you think about translating "Runner" itself, could be "Anwendungsstarter"?

Could be done, yes. In particular as it's handled in a similar manner regarding plugin-quicklaunch.

How about my thoughts regarding "Appearance" (see previous comment)?

**Comment by ThomasVie** [comment]
Yes, "Positioning" would be better.

**Comment by pmattern** [comment]
So I suggest you add the hyphen and trade Runner with Anwendungsstarter as discussed. Maybe the term can even get dropped at some locations where it's obvious, e. g. [here](https://github.com/ThomasVie/lxqt-runner/blob/82a94cb6048a638a3c8dcbb8d6864f4ae119e70c/translations/lxqt-runner_de.ts#L77) so as to keep things clear.
If you squash this into this commit I'd merge, that appearance thing should be discussed elsewhere as it's affecting all translations as well as the template.

**Comment by ThomasVie** [comment]
Rebased and squashed.

**Pull request merged**
