### PR TITLE
fallback for executing scripts w/o #!

### PR DESCRIPTION
**Pull request by palinek**
Fixes lxde/lxqt#15 similary as @eerden in lxde/lxqt-runner#6, but only as fallback mechanism...

### CODE REVIEW

**Comment by paulolieuthier** [comment]
Awesome.

**Comment by palinek** [comment]
Just that we are clear about this one: I'm not 100% sure about wordexp, but with this impelmentation user can input any "shell" command(s) into runner and it/they will be successfully executed?
Is this a good feature or a new bug?

**Comment by palinek** [comment]
...just tested... the "shell injection" is not happenning

**Comment by paulolieuthier** [comment]
I thought you had fixed the issue. I remember trying to fix it unsuccesfully before. lxqt-runner's providers are not very simple. And yes, it's possible to run a shell directly.

**Comment by palinek** [comment]
I still think it's been fixed this way. For me everything seems to work. What's wrong with it?

**Comment by paulolieuthier** [comment]
I misunderstood what you said. Thanks for this one. I'll merge it soon.

**Pull request merged**
